BDO/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^requests/', include('userrequests.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userrequests/urls.py
from django.conf.urls import url
from . import views

app_name = 'userrequests'

urlpatterns = [

    # requests/
    url(r'^$', views.IndexList.as_view(), name='index'),

    # requests/users
    url(r'^users/$', views.ajaxcall, name='fetchd'),

    # requests/462/
    url(r'^(?P<pk>[0-9]+)/$', views.Detail.as_view(), name='detail'),

    # requests/searchres/
    url(r'^searchres/$', views.SearchView.as_view(), name='search'),

    # requests/463/discussion/
    url(r'^(?P<pk>[0-9]+)/discussion/$', views.Discussion.as_view(), name='reqdiscusion'),

    # requests/444/discussion/close
    url(r'^(?P<pk>[0-9]+)/discussion/close$', views.closeRequest, name='closereq'),

    # requests/create/
    url(r'^create/$', views.Create.as_view(), name='create'),

    # requests/345/update
    url(r'^(?P<pk>[0-9]+)/update/$', views.Update.as_view(), name='update'),

    # login/
    url(r'^login/$', views.UserLogin.as_view(), name='login'),

    # register/
    url(r'^register/$', views.UserFormView.as_view(), name='register'),

    # logout/
    url(r'^logout/$', views.UserLogout, name='user-logout'),

]

userrequests/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

class UserRequests(models.Model):

    SERVICE_TYPE = (
        ('CD', 'Custom Data'),
        ('RP', 'Report'),
    )
    CATEGORY_TYPE = (
        ('C1', 'Category 1'),
        ('C2', 'Category 2'),
        ('C3', 'Category 3'),
    )
    PROVIDERS = (
        ('NT', 'NTUA'),
        ('EX', 'EXHILE'),
        ('AL', 'Every BDO Provider'),
    )
    user = models.CharField(max_length=20)
    title = models.CharField(max_length=50)
    keywords = models.TextField(max_length=500)
    service_description = models.TextField(max_length=500)
    service_type = models.CharField(max_length=2, choices=SERVICE_TYPE, default='CD')
    deadline = models.DateField(default=date.today())
    budget = models.IntegerField()
    file = models.FileField(upload_to='images/')
    category_type = models.CharField(max_length=2, choices=CATEGORY_TYPE, default='C1')
    provider = models.CharField(max_length=2, choices=PROVIDERS, default='NT')
    email_notification = models.BooleanField(default=False)
    closed = models.BooleanField(default=False)
    views = models.IntegerField(default=0)
    downloads = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Messages(models.Model):

    userreq = models.CharField(max_length=20)
    userpost = models.CharField(max_length=20)
    requestid = models.ForeignKey(UserRequests)
    message = models.TextField(max_length=500)
    date = models.DateTimeField(auto_now_add=True, blank=False)
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

    def __str__(self):
        return self.message + " by: " + self.userpost

class MessageNotify(models.Model):

    user = models.CharField(max_length=20)
    messageid = models.ForeignKey(Messages)

userrequests/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import UserRequests, Messages


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password', 'email']

class UserLoginForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput)



class RequestForm(forms.ModelForm):
    file = forms.FileField(required=False)
    deadline = forms.DateField(widget=forms.widgets.DateInput(attrs={'type': 'date'}))

    class Meta:
        model = UserRequests
        exclude = ['user', 'views', 'downloads', 'closed']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Give A Descriptive Title'}),
            'keywords': forms.Textarea(attrs={'cols': 40, 'rows': 3, 'style': 'resize:none;',
                                                    'placeholder': 'Provide Keywords Seperated With "," '}),
            'service_description': forms.Textarea(attrs={'cols': 40, 'rows': 5, 'style': 'resize:none;',
                                                    'placeholder': 'Give A Description About Your Request'}),
        }


class MessageForm(forms.ModelForm):

    class Meta:
        model = Messages
        fields = ['message']

userrequests/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.renderers import TemplateHTMLRenderer, JSONRenderer
from rest_framework.utils import json
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from django.http import Http404, JsonResponse, HttpResponse
from .models import UserRequests, Messages
from .forms import UserForm, UserLoginForm, RequestForm, MessageForm
from .serializers import UserRequestsSerializer, MessagesSerializer, MessageNotifySerializer
from django.contrib.auth import authenticate, login, logout
from django.views import generic
from django.shortcuts import redirect
from django.shortcuts import render


# Create your views here.

#requests/
class IndexList(APIView):
    template_name = "userrequests/index.html"
    renderer_classes = (TemplateHTMLRenderer,)

    def get(self, request):
        user = self.request.user
        if user.is_authenticated:
            open = UserRequests.objects.filter(closed=False).order_by('-deadline')
            openser = UserRequestsSerializer(open, many=True)
            closed = UserRequests.objects.filter(closed=True).order_by('-deadline')
            closedser = UserRequestsSerializer(closed, many=True)
            all_requests = open.count() + closed.count()
            return Response({'all_requests': all_requests, 'open': openser.data, 'closed': closedser.data},
                            template_name="index.html")
            #return render(request, self.template_name, {'all_requests': serializer.data, 'open': openser.data, 'closed': closedser.data})
        else:
            return Response(None, template_name="index.html")
            #return render(request, self.template_name, {'all_requests': None})


    def post(self, request):
        serializer = UserRequestsSerializer(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


def ajaxcall(request):
    if request.method == 'GET':
        mode = request.GET['mode']
        if mode == 'user':
            user = request.user
            open = UserRequests.objects.filter(user=user.username, closed=False)
            openser = UserRequestsSerializer(open, many=True)
            closed = UserRequests.objects.filter(user=user.username, closed=True)
            closedser = UserRequestsSerializer(closed, many=True)
            sum = open.count() + closed.count()
            return JsonResponse({'open': openser.data, 'closed': closedser.data, 'sum': sum},
                                content_type="application/json")
        elif mode == 'all':
            open = UserRequests.objects.filter(closed=False)
            openser = UserRequestsSerializer(open, many=True)
            closed = UserRequests.objects.filter(closed=True)
            closedser = UserRequestsSerializer(closed, many=True)
            sum = open.count() + closed.count()
            return JsonResponse({'open': openser.data, 'closed': closedser.data, 'sum': sum},
                                content_type="application/json")
        elif mode == 'search':
            title = request.GET['title']
            try:
                open = UserRequests.objects.filter(title=title, closed=False)
            except UserRequests.DoesNotExist:
                open = ""
            openser = UserRequestsSerializer(open, many=True)
            try:
                closed = UserRequests.objects.filter(title=title, closed=True)
            except UserRequests.DoesNotExist:
                closed = ""
            closedser = UserRequestsSerializer(closed, many=True)
            sum = open.count() + closed.count()
            return JsonResponse({'open': openser.data, 'closed': closedser.data, 'sum': sum},
                                content_type="application/json")
        else:
            return HttpResponse("Invalid Mode Selection")
    else:
        return HttpResponse("Request method is not a GET")


class Detail(APIView):
    template_name = "userrequests/detail.html"
    renderer_classes = (TemplateHTMLRenderer,)
    entry = UserRequests

    def get_object(self, pk):
        try:
            return UserRequests.objects.get(pk=pk)
        except UserRequests.DoesNotExist:
            raise Http404

    def get_keywords(self, keywords):
        keys_list = []
        try:
            keys_list = keywords.split(',')
            return keys_list
        except UserRequests.DoesNotExist:
            raise Http404

    def clear_duplicates(self, list):
        clear_list = []
        for entry in list:
            if entry not in clear_list:
                clear_list.append(entry)
        return clear_list


    def get(self, request, pk):
        entry = self.get_object(pk)
        user = self.request.user
        serializer = UserRequestsSerializer(entry)
        prev = UserRequests.objects.filter(user=user.username)
        prevser = UserRequestsSerializer(prev, many=True)
        list = self.get_keywords(entry.keywords)
        related = []
        for key in list:
            current_results = UserRequests.objects.filter(keywords__icontains=key).exclude(pk=entry.pk)
            relatedser = UserRequestsSerializer(current_results, many=True)
            related += relatedser.data
        related = self.clear_duplicates(related)
        #related = UserRequests.objects.filter(keywords__icontains=entry.keywords).exclude(pk=entry.pk)

        return Response({'index': serializer.data, 'prev': prevser.data, 'related': related},
                        template_name="detail.html")
        #return render(request, self.template_name,
         #             {'index': serializer.data, 'prev': prevser.data, 'related': relatedser.data})

    def put(self, request, pk):
        snippet = self.get_object(pk)
        serializer = UserRequestsSerializer(snippet, data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def delete(self, request, pk):
        snippet = self.get_object(pk)
        snippet.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

class SearchView(APIView):
    template_name = "userrequests/searchres.html"
    renderer_classes = (TemplateHTMLRenderer,)

    def get_object(self, title):
        try:
            return UserRequests.objects.filter(title=title)
        except UserRequests.DoesNotExist:
            return None

    def get(self, request):
        title = request.GET['title']
        results = self.get_object(title)
        resser = UserRequestsSerializer(results, many=True)

        return Response({'results': resser.data}, template_name="searchres.html")



class Create(APIView):
    template_name = "userrequests/userrequests_form.html"
    renderer_classes = (TemplateHTMLRenderer,)
    parser_classes = (FormParser, MultiPartParser)
    form_class = RequestForm

    def get_object(self, pk):
        try:
            return UserRequests.objects.get(pk=pk)
        except UserRequests.DoesNotExist:
            raise Http404

    def get(self, request):
        form = self.form_class(None)
        return Response({'form': form, 'entry': None}, template_name="userrequests_form.html")
        #return render(request, self.template_name, {'form': form})

    def post(self, request, format=None):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            data = request.data
            serializer = UserRequestsSerializer(data=data, context={'request': request})
            serializer.user = self.request.user.username  # use your own profile here
            serializer.file = self.request.FILES
            if serializer.is_valid():
                entry = serializer.save(user=request.user.username)
                return redirect('userrequests:detail', entry.id)
            error_message = serializer.errors
            #return render(request, self.template_name, {'form': form, 'error_message': error_message, 'entry': request.data})
            return Response({'form': form, 'error_message': error_message, 'entry': None},
                                          template_name="userrequests_form.html")
        error_message = "Form Not Valid. Please Retry"
        return Response({'form': form, 'error_message': error_message, 'entry': None},
                        template_name="userrequests_form.html")
        #return render(request, self.template_name, {'form': form, 'error_message': error_message, 'entry': request.data})

class Update(APIView):

    template_name = "userrequests/userrequests_form.html"
    renderer_classes = (TemplateHTMLRenderer,)
    parser_classes = (FormParser, MultiPartParser)
    form_class = RequestForm

    def get_object(self, pk):
        try:
            return UserRequests.objects.get(pk=pk)
        except UserRequests.DoesNotExist:
            raise Http404

    def get(self, request, pk):
        entry = self.get_object(pk)
        form = self.form_class(instance=entry)
        return Response({'form': form, 'entry': entry}, template_name="userrequests_form.html")

    def post(self, request, pk, format=None):
        entry = self.get_object(pk=pk)
        form = self.form_class(request.POST, request.FILES, instance=entry)

        if form.is_valid():
            serializer = UserRequestsSerializer(entry, data=request.data, context={'request': request})
            serializer.user = self.request.user.username  # use your own profile here
            serializer.file = entry.file

            if serializer.is_valid():
                entry = serializer.save(user=request.user.username)

userrequests/templates/userrequests/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%  block title %}User Requests{% endblock %}</title>

    {% load staticfiles %}

    <!-- Bootstrap library -->
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

	<!-- Latest compiled JavaScript -->
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'userrequests/styles.css' %}"/>

    {% block script %}{% endblock %}

</head>
<body>


        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#menu">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'userrequests:index' %}">BigDataOcean</a>
                </div>
                <div class="collapse navbar-collapse" id="menu">
                    <ul class="nav navbar-nav">
                        <li>
                            <a href="#">
                                Usability1
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Usability2
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Usability3
                            </a>
                        </li>
                        <li class="dropdown
                            {% if request.path == "/requests/create" or request.path == "/requests/" %}
                               active
                            {% endif %}">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="reqmenu">
                                <span class="caret"></span> Requests
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a href="{% url 'userrequests:create' %}">Create A Request</a>
                                </li>
                                <li>
                                    <a href="{% url 'userrequests:index' %}">Requests Data</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <form class="navbar-form navbar-right" role="search" method="GET" action="#">
                                <div class="form-group  is-empty">
                                    <input type="text" class="form-control border-input" placeholder="" name="q">
                                    <span class="material-input"></span>
                                    <span class="material-input"></span>
                                </div>
                                <button type="submit" class="btn btn-white btn-round btn-just-icon">
                                    <i class="material-icons">search</i>
                                    <div class="ripple-container">
                                    </div>
                                </button>
                            </form>
                        </li>
                        <li>
                            {% if request.user.is_authenticated %}
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span class="glyphicon glyphicon-user"></span>
                                    Hello {{ request.user.username }}
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{% url 'userrequests:user-logout' %}">
                                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
                                            Logout
                                        </a>
                                    </li>
                                </ul>
                            {% else %}
                                <a href="{% url 'userrequests:login' %}">
                                    <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>
                                    Login
                                </a>
                            {% endif %}
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

            <!-- content when window is in it's original size : contains both horizontal and vertical navigations bars and the main content -->

        <div class="jumbotron">
            <div id="content" class="container">

                {% block body %}
                {% endblock %}

            </div>
        </div>


</body>

</html>

userrequests/templates/userrequests/detail.html
{% extends 'userrequests/base.html' %}

{% block title %}Request Details{% endblock %}

{% block body %}

    <div class="container-fluid">

        <ul class="breadcrumb">
            <li><a href="{% url 'userrequests:index' %}">Requests</a></li>
            <li><a href="#">{{ index.title }}</a></li>
        </ul>

        <h1 class="text-center">On Demand Data Services</h1>
        <div class="container" id="detailbox">
            <div class="row">
                <h2 style="display: inline;">{{ index.title }}</h2>
                <a style="float: right; display: inline; margin-right: 20px;" href="{% url 'userrequests:reqdiscusion' index.id %}">
                    <button type="submit" class="btn btn-success">
                        View Discussion
                        <span class="glyphicon glyphicon-edit" style="color: white" aria-hidden="true"></span>
                    </button>
                </a>
                <hr>
                <div class="col-sm-7">
                    <p style="color: grey">{{ index.views }} views/ {{ index.downloads }} downloads</p>
                    <img src="{{ index.file }}" width="100px" height="100px" alt="No File Has Been Uploaded" style="color: brown; float: left; margin-right: 40px;">
                    <p style="display: inline">
                        <h4>Provider : {{ index.provider }}</h4>
                        <h5>Service Type : {{ index.service_type }}</h5>
                    </p>
                    <br style="clear: both">
                    <h3>Keywords : </h3>
                    <textarea rows="2" cols="40" style="resize: none" disabled>{{ index.keywords }}</textarea>
                    <h4>Service Description : </h4>
                    <textarea rows="3" cols="40" style="resize: none;" disabled>{{ index.service_description }}</textarea>

                </div>

                <div class="col-sm-3">
                    <a href="#">
                        <button type="submit" class="btn btn-default">
                            Contact the Provider
                            <span class="glyphicon glyphicon-envelope" style="color: darkcyan" aria-hidden="true"></span>
                        </button>
                    </a>
                    <h5>Category Type : {{ index.category_type }}</h5>
                    <h3>DeadLine : <span style="color: darkred;">{{ index.deadline }}</span></h3>
                    <h3>Budget : {{ index.budget }}</h3>
                    <h4>Answered : {{ index.closed }}</h4>
                </div>
            </div>
            {% if request.user.is_authenticated %}
                {% if request.user.username == index.user %}
                    <div class="col-sm-offset-5">
                        <a id="update" href="{% url 'userrequests:update' index.id %}">
                            <button type="submit" class="btn btn-lg btn-primary">
                                Update Request
                                <span class="glyphicon glyphicon-edit" aria-hidden="true"></span>
                            </button>
                        </a>
                    </div>
                {% endif %}
            {% endif %}
        </div>
        <br>
        <div class="container-fluid">
            <div id="prev" class="col-sm-5 col-sm-offset-1">
                {% if prev|length > 0 %}
                    <h3 class="text-center">Your Previous Requests</h3>
                    <div id="prevt" class='table-wrapper'>
                        <table id='previous' class='table table-hover'>
                            <tbody id='otbody'>
                                {% for entry in prev %}
                                    {% if entry.id != index.id %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'userrequests:detail' entry.id %}">
                                                    <h4>{{ entry.title }}</h4>
                                                </a>
                                            </td>
                                            <td>
                                                <p>{{ entry.keywords }}</p>
                                            </td>
                                            <td>
                                                <p>{{ entry.deadline }}</p>
                                            </td>
                                            <td>
                                                {% if entry.closed %}
                                                    <span class="glyphicon glyphicon-ok" style="color: green; float: right;"></span></p>
                                                {% else %}
                                                    <span class="glyphicon glyphicon-time" style="color: blue; float: right;"></span></p>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endif %}
                                {%  endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <h3 class="text-center">You Have Not Other Requests</h3>
                {% endif %}
            </div>
            <div class="col-sm-5">
                {% if related|length > 0 %}
                    <h3 class="text-center">Related Requests ({{ related|length }})</h3>
                    <div id="relatedt" class='table-wrapper'>
                        <table id='related' class='table table-hover'>
                            <tbody id='rtbody'>
                                {% for entry in related %}
                                    {% if entry.id != index.id %}
                                        <tr>
                                            <td>
                                                <a href="{% url 'userrequests:detail' entry.id %}">
                                                    <h4>{{ entry.title }}</h4>
                                                </a>
                                            </td>
                                            <td>
                                                <p>{{ entry.keywords }}</p>
                                            </td>
                                            <td>
                                                <p>{{ entry.user }}</p>
                                            </td>
                                            <td>
                                                {% if entry.closed %}
                                                    <span class="glyphicon glyphicon-ok" style="color: green; float: right;"></span></p>
                                                {% else %}
                                                    <span class="glyphicon glyphicon-time" style="color: blue; float: right;"></span></p>
                                                {% endif %}
                                            </td>
                                        </tr>
                                    {% endif %}
                                {%  endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <h3 class="text-center">We Have Not Found A Common Request</h3>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

userrequests/templates/userrequests/login_form-template.html
<div class="form-group">
    {% for field in form %}
        <label>
            {{ field.label_tag }}
        </label>
        <div>
            {{ field }}
        </div>
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
    {% endfor %}
</div>

userrequests/templates/userrequests/searchres.html
{% extends 'userrequests/base.html' %}
{% block title %}Search Results{% endblock %}

{% block body %}

<div id="container" class="container-fluid text-center">
    <!-- Displays the Search Results If Any -->
    {%  if results|length > 0 %}
        <h1>Search Results</h1>
        <form class="navbar-form" role="search" method="GET" action="{% url 'userrequests:search' %}">
            <div class="form-group  is-empty">
                <input type="text" class="form-control border-input" placeholder="Search For A Request" name="title">
            </div>
            <button type="submit" class="btn btn-default">
                Search
                <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
            </button>
        </form>

        <h1>({{ results|length }}) Search Results</h1>

        <div id="results">
            {% if results|length > 0 %}
                <div class='table-wrapper'>
                    <table id='restable' class='table table-hover'>
                        <tbody id='rtbody'>
                            {% for entry in results %}
                                <tr>
                                    <td>
                                        <a href="{%  url 'userrequests:detail' entry.id %}">
                                            <img src="{{ entry.file }}" width="100px" height="100px" alt="No Image Has Been Uploaded" style="color: brown; float: left; margin-right: 40px;">
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{% url 'userrequests:detail' entry.id %}">
                                            <h4 class="text-left">{{ forloop.counter }} : {{ entry.title }}</h4>
                                        </a>
                                    </td>
                                    <td>
                                        <p>{{ entry.keywords }}</p>
                                    </td>
                                    <td>
                                        <p>{{ entry.service_description }}</p>
                                    </td>
                                    <td>
                                        <p>{{ entry.service_type }}</p>
                                    </td>
                                </tr>
                            {%  endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h4>You Have No Pending Request</h4>
            {% endif %}
        </div>

    <!-- Content When User Has No Requests Yet -->
    {%  else %}
        <h2>No Results Were Found With The Given Title</h2>
        <br>
        <h4>Be The First To Make The Request!</h4>
        <a href="{% url 'userrequests:create' %}">
            <button type="submit" class="btn btn-lg btn-primary">
                Create A Request
                <span class="glyphicon glyphicon-check" aria-hidden="true"></span>
            </button>
        </a>
    {%  endif %}

</div>

{% endblock %}